resolver: lts-7.7
packages:
- '.'
- location:
    git: https://github.com/ancientlanguage/haskell-primary-type.git
    commit: f4a775b9986385e5cd768c680098495445301b1b
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-grammar.git
    commit: dcdf6b9a82ece55173e48d436c5d52398929b35f
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
