resolver: lts-7.9
packages:
- '.'
- location:
    git: https://github.com/ancientlanguage/haskell-primary-type.git
    commit: bf5642c7641ba149182e380795b95e5aba58471e
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-grammar.git
    commit: b0712b8422e301d955d396f00cb67cea6d9ad8c6
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-greek-script.git
    commit: aebd905543ab609a5c955595e4cf4c65fac4e9ed
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
