resolver: lts-7.7
packages:
- '.'
- location:
    git: https://github.com/ancientlanguage/haskell-primary-type.git
    commit: f4a775b9986385e5cd768c680098495445301b1b
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-grammar.git
    commit: b2df7ee4e8d55f47939ee27dc45f9606ffe78a22
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-greek-script.git
    commit: 4c556901c37010fd5e4860ca32c908a67d644ec8
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
