resolver: lts-7.7
packages:
- '.'
- location:
    git: https://github.com/ancientlanguage/haskell-primary-type.git
    commit: f4a775b9986385e5cd768c680098495445301b1b
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-grammar.git
    commit: 7e74d35f53788b5edc54343e38dc2162b36c2bde
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
