resolver: lts-7.7
packages:
- '.'
- location:
    git: https://github.com/ancientlanguage/haskell-primary-type.git
    commit: f4a775b9986385e5cd768c680098495445301b1b
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-grammar.git
    commit: bf0d6e2af5816083000d65fe836b990f250860be
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
