resolver: lts-7.7
packages:
- '.'
- location:
    git: https://github.com/ancientlanguage/haskell-primary-type.git
    commit: f4a775b9986385e5cd768c680098495445301b1b
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-grammar.git
    commit: 44272b0d2524ece82b81c351bb17e53ce40b88a0
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
