resolver: lts-7.7
packages:
- '.'
- location:
    git: https://github.com/ancientlanguage/haskell-primary-type.git
    commit: f4a775b9986385e5cd768c680098495445301b1b
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-grammar.git
    commit: 463d6e3dfab1354eb03fdc18cf42227269fd5d0d
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
