resolver: lts-7.7
packages:
- '.'
- location:
    git: https://github.com/ancientlanguage/haskell-primary-type.git
    commit: f4a775b9986385e5cd768c680098495445301b1b
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-grammar.git
    commit: 387774d8c5cc5d346f3757d09117232f9b39d3cd
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-greek-script.git
    commit: f4f8f299a03fa275b4039de61f083697686e8e68
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
