resolver: lts-7.9
packages:
- '.'
- location:
    git: https://github.com/ancientlanguage/haskell-primary-type.git
    commit: ec0d771f98d1a0f61c42dfbdc3d5a40965753bde
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-grammar.git
    commit: c42c4b23d3195c649355a60c66008a7126e2e941
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
