resolver: lts-7.7
packages:
- '.'
- location:
    git: https://github.com/ancientlanguage/haskell-primary-type.git
    commit: f4a775b9986385e5cd768c680098495445301b1b
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-grammar.git
    commit: e8554241c2324fb9f00073cb384d4620ebe7f4f5
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-greek-script.git
    commit: c3c982dbd28e35f5869b0fcb64925d2ef5a25290
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
