resolver: lts-7.7
packages:
- '.'
- location:
    git: https://github.com/ancientlanguage/haskell-primary-type.git
    commit: f4a775b9986385e5cd768c680098495445301b1b
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-grammar.git
    commit: b4e9d150c784106cc4a7acd768d05427cbf4d81c
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-greek-script.git
    commit: 0aa6788ca98ebea41ed35185e1ab764c097baa27
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
