resolver: lts-7.7
packages:
- '.'
- location:
    git: https://github.com/ancientlanguage/haskell-primary-type.git
    commit: f4a775b9986385e5cd768c680098495445301b1b
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-grammar.git
    commit: f96d807b2f88d8213e7003bb18730026548cfc7b
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
