resolver: lts-7.9
packages:
- '.'
- location:
    git: https://github.com/ancientlanguage/haskell-primary-type.git
    commit: ec0d771f98d1a0f61c42dfbdc3d5a40965753bde
  extra-dep: true
- location:
    git: https://github.com/ancientlanguage/haskell-grammar.git
    commit: 6d24373e88648e0d51f2c92eeb45877e6fc71175
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
