module Grammar.Greek.Script.Rounds.SymbolLetter where

import Grammar.Round
import Grammar.CommonTypes
import Grammar.Greek.Script.Types

symbolLetter :: RoundId Symbol (Letter :* Case :* Final)
symbolLetter = RoundId to from
  where
  to S_Α = (L_α, (Uppercase, NotFinal))
  to S_Β = (L_β, (Uppercase, NotFinal))
  to S_Γ = (L_γ, (Uppercase, NotFinal))
  to S_Δ = (L_δ, (Uppercase, NotFinal))
  to S_Ε = (L_ε, (Uppercase, NotFinal))
  to S_Ζ = (L_ζ, (Uppercase, NotFinal))
  to S_Η = (L_η, (Uppercase, NotFinal))
  to S_Θ = (L_θ, (Uppercase, NotFinal))
  to S_Ι = (L_ι, (Uppercase, NotFinal))
  to S_Κ = (L_κ, (Uppercase, NotFinal))
  to S_Λ = (L_λ, (Uppercase, NotFinal))
  to S_Μ = (L_μ, (Uppercase, NotFinal))
  to S_Ν = (L_ν, (Uppercase, NotFinal))
  to S_Ξ = (L_ξ, (Uppercase, NotFinal))
  to S_Ο = (L_ο, (Uppercase, NotFinal))
  to S_Π = (L_π, (Uppercase, NotFinal))
  to S_Ρ = (L_ρ, (Uppercase, NotFinal))
  to S_Σ = (L_σ, (Uppercase, NotFinal))
  to S_Τ = (L_τ, (Uppercase, NotFinal))
  to S_Υ = (L_υ, (Uppercase, NotFinal))
  to S_Φ = (L_φ, (Uppercase, NotFinal))
  to S_Χ = (L_χ, (Uppercase, NotFinal))
  to S_Ψ = (L_ψ, (Uppercase, NotFinal))
  to S_Ω = (L_ω, (Uppercase, NotFinal))
  to S_α = (L_α, (Lowercase, NotFinal))
  to S_β = (L_β, (Lowercase, NotFinal))
  to S_γ = (L_γ, (Lowercase, NotFinal))
  to S_δ = (L_δ, (Lowercase, NotFinal))
  to S_ε = (L_ε, (Lowercase, NotFinal))
  to S_ζ = (L_ζ, (Lowercase, NotFinal))
  to S_η = (L_η, (Lowercase, NotFinal))
  to S_θ = (L_θ, (Lowercase, NotFinal))
  to S_ι = (L_ι, (Lowercase, NotFinal))
  to S_κ = (L_κ, (Lowercase, NotFinal))
  to S_λ = (L_λ, (Lowercase, NotFinal))
  to S_μ = (L_μ, (Lowercase, NotFinal))
  to S_ν = (L_ν, (Lowercase, NotFinal))
  to S_ξ = (L_ξ, (Lowercase, NotFinal))
  to S_ο = (L_ο, (Lowercase, NotFinal))
  to S_π = (L_π, (Lowercase, NotFinal))
  to S_ρ = (L_ρ, (Lowercase, NotFinal))
  to S_σ = (L_σ, (Lowercase, NotFinal))
  to S_ς = (L_σ, (Lowercase, IsFinal))
  to S_τ = (L_τ, (Lowercase, NotFinal))
  to S_υ = (L_υ, (Lowercase, NotFinal))
  to S_φ = (L_φ, (Lowercase, NotFinal))
  to S_χ = (L_χ, (Lowercase, NotFinal))
  to S_ψ = (L_ψ, (Lowercase, NotFinal))
  to S_ω = (L_ω, (Lowercase, NotFinal))

  from (L_α, (Uppercase, _)) = S_Α
  from (L_β, (Uppercase, _)) = S_Β
  from (L_γ, (Uppercase, _)) = S_Γ
  from (L_δ, (Uppercase, _)) = S_Δ
  from (L_ε, (Uppercase, _)) = S_Ε
  from (L_ζ, (Uppercase, _)) = S_Ζ
  from (L_η, (Uppercase, _)) = S_Η
  from (L_θ, (Uppercase, _)) = S_Θ
  from (L_ι, (Uppercase, _)) = S_Ι
  from (L_κ, (Uppercase, _)) = S_Κ
  from (L_λ, (Uppercase, _)) = S_Λ
  from (L_μ, (Uppercase, _)) = S_Μ
  from (L_ν, (Uppercase, _)) = S_Ν
  from (L_ξ, (Uppercase, _)) = S_Ξ
  from (L_ο, (Uppercase, _)) = S_Ο
  from (L_π, (Uppercase, _)) = S_Π
  from (L_ρ, (Uppercase, _)) = S_Ρ
  from (L_σ, (Uppercase, _)) = S_Σ
  from (L_τ, (Uppercase, _)) = S_Τ
  from (L_υ, (Uppercase, _)) = S_Υ
  from (L_φ, (Uppercase, _)) = S_Φ
  from (L_χ, (Uppercase, _)) = S_Χ
  from (L_ψ, (Uppercase, _)) = S_Ψ
  from (L_ω, (Uppercase, _)) = S_Ω
  from (L_α, (Lowercase, _)) = S_α
  from (L_β, (Lowercase, _)) = S_β
  from (L_γ, (Lowercase, _)) = S_γ
  from (L_δ, (Lowercase, _)) = S_δ
  from (L_ε, (Lowercase, _)) = S_ε
  from (L_ζ, (Lowercase, _)) = S_ζ
  from (L_η, (Lowercase, _)) = S_η
  from (L_θ, (Lowercase, _)) = S_θ
  from (L_ι, (Lowercase, _)) = S_ι
  from (L_κ, (Lowercase, _)) = S_κ
  from (L_λ, (Lowercase, _)) = S_λ
  from (L_μ, (Lowercase, _)) = S_μ
  from (L_ν, (Lowercase, _)) = S_ν
  from (L_ξ, (Lowercase, _)) = S_ξ
  from (L_ο, (Lowercase, _)) = S_ο
  from (L_π, (Lowercase, _)) = S_π
  from (L_ρ, (Lowercase, _)) = S_ρ
  from (L_σ, (Lowercase, IsFinal)) = S_ς
  from (L_σ, (Lowercase, _)) = S_σ
  from (L_τ, (Lowercase, _)) = S_τ
  from (L_υ, (Lowercase, _)) = S_υ
  from (L_φ, (Lowercase, _)) = S_φ
  from (L_χ, (Lowercase, _)) = S_χ
  from (L_ψ, (Lowercase, _)) = S_ψ
  from (L_ω, (Lowercase, _)) = S_ω
